#! /usr/bin/env python

import argparse
from chemeco import ChemEcoRun

parser = argparse.ArgumentParser(
    description=
    "ChemEco runs an input file that follows the instructions to describe the data mining workflow."
)
parser.add_argument(
    "-i",
    type=str,
    required=True,
    help="input file: path to the ChemEco's input file name and its format."
)
parser.add_argument(
    "-o",
    type=str,
    required=True,
    help=
    "output directory: path to the output directory. If it's not unique an incremental foldername will be created."
)
args = parser.parse_args()
SCRIPT_NAME = args.i
output_directory = args.o

ChemEcoRun(INPUT_FILE=SCRIPT_NAME, OUTPUT_DIRECTORY=output_directory)
